name: lexxi
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.39+39

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^7.5.0
  provider: ^6.0.5
  sizer: ^2.0.15
  google_fonts: ^4.0.0
  rive: ^0.13.8
  flutter_switch: ^0.3.2
  sliding_up_panel2: ^3.3.0+1
  jwt_decode_full: ^0.9.2
  get_it: ^7.6.4
  injectable: ^2.3.0
  motion_toast: ^2.7.8
  shared_preferences: ^2.2.1
  loading_animation_widget: ^1.2.0+4
  flutter_html: ^3.0.0-beta.2
  logger: ^2.0.2+1
  flutter_local_notifications: ^19.4.2
  timezone: ^0.10.1
  html: ^0.15.4
  flutter_tex: ^4.0.6
  url_launcher: ^6.3.0
  whatsapp_unilink: ^2.1.0
  photo_view: ^0.14.0
  animated_text_kit: ^4.2.2
  http: ^1.2.1
  # cloud_firestore: ^5.4.2
  # firebase_core: ^3.5.0
  fleather: ^1.25.1
  video_player: ^2.8.6
  audioplayers: ^6.0.0
  flutter_animate: ^3.0.0
  collection: ^1.18.0
  # firebase_messaging: ^15.1.2
  intl: ^0.20.2
  flutter_math_fork: ^0.7.4
  confetti: ^0.8.0
  reward_popup: ^0.0.7
  h_alert_dialog: ^1.1.2
  flutter_svg_provider: ^1.0.7
  image_picker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/videos/Calendario-B2025_1.mp4